from django.contrib import admin
from django.urls import path, include

from core.views import home, PanelAdminView, PanelConsorcistView
from consorcios.views import (
    MisExpensasView,
    DetalleExpensaConsorcistView,
    informar_pago,
    CrearSolicitudView,
    ListarSolicitudesView,
    gestionar_solicitud,
    retirar_permisos,
    ListarConsorciosView,
    CrearConsorcioView,
    EditarConsorcioView,
    EliminarConsorcioView,
    ListarDepartamentosView,
    CrearDepartamentoView,
    EditarDepartamentoView,
    EliminarDepartamentoView,
    ListarTitularidadesView,
    CrearTitularidadView,
    EditarTitularidadView,
    EliminarTitularidadView,
)
from expensas.views import (
    ListarExpensasView,
    DetalleExpensaView,
    CrearExpensaView,
    EditarExpensaView,
    EliminarExpensaView,
    SeleccionarPreviewView,
    PreviewPeriodoView,
    enviar_expensas,
    ListarProveedoresView,
    CrearProveedorView,
    EditarProveedorView,
    EliminarProveedorView,
    ListarGastosView,
    CrearGastoView,
    EditarGastoView,
    EliminarGastoView,
)
from usuarios.views import (
    redirigir_segun_rol,
    registro,
    ListarPerfilesView,
    CrearPerfilView,
    EditarPerfilView,
    EliminarPerfilView,
    ListarUsuariosView,
    CrearUsuarioView,
    EditarUsuarioView,
    EliminarUsuarioView,
)
from reclamos.views import (
    CrearReclamoView,
    MisReclamosView,
    ListarReclamosView,
    actualizar_estado,
)
from avisos.views import (
    ListarAvisosAdminView,
    CrearAvisoView,
    EditarAvisoView,
    MisAvisosView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', home, name='home'),
    path('registro/', registro, name='registro'),
    path('redirigir/', redirigir_segun_rol, name='redirigir_segun_rol'),
    path('panel-admin/', PanelAdminView.as_view(), name='panel_admin'),
    path('panel-consorcista/', PanelConsorcistView.as_view(), name='panel_consorcista'),
    path('mis-expensas/', MisExpensasView.as_view(), name='mis_expensas'),
    path('mis-expensas/<int:expensa_id>/', DetalleExpensaConsorcistView.as_view(), name='detalle_expensa_consorcista'),
    path('informar-pago/<int:expensa_id>/', informar_pago, name='informar_pago'),
    path('solicitud/', CrearSolicitudView.as_view(), name='crear_solicitud'),
    path('solicitudes/', ListarSolicitudesView.as_view(), name='listar_solicitudes'),
    path('solicitudes/<int:solicitud_id>/', gestionar_solicitud, name='gestionar_solicitud'),
    path('solicitudes/retirar/<int:solicitud_id>/', retirar_permisos, name='retirar_permisos'),
    path('listar-expensas/', ListarExpensasView.as_view(), name='listar_expensas'),
    path('expensa/<int:expensa_id>/', DetalleExpensaView.as_view(), name='detalle_expensa'),
    path('crear-expensa/', CrearExpensaView.as_view(), name='crear_expensa'),
    path('editar-expensa/<int:expensa_id>/', EditarExpensaView.as_view(), name='editar_expensa'),
    path('eliminar-expensa/<int:expensa_id>/', EliminarExpensaView.as_view(), name='eliminar_expensas'),
    path('generar-expensas/', SeleccionarPreviewView.as_view(), name='seleccionar_preview'),
    path('preview/<int:consorcio_id>/<str:periodo>/', PreviewPeriodoView.as_view(), name='preview_periodo'),
    path('enviar-expensas/<int:consorcio_id>/<str:periodo>/', enviar_expensas, name='enviar_expensas'),
    path('mis-reclamos/', MisReclamosView.as_view(), name='mis_reclamos'),
    path('crear-reclamo/', CrearReclamoView.as_view(), name='crear_reclamo'),
    path('reclamos/', ListarReclamosView.as_view(), name='listar_reclamos'),
    path('reclamos/actualizar/<int:reclamo_id>/', actualizar_estado, name='actualizar_estado'),
    path('avisos/', ListarAvisosAdminView.as_view(), name='listar_avisos_admin'),
    path('avisos/nuevo/', CrearAvisoView.as_view(), name='crear_aviso'),
    path('avisos/editar/<int:aviso_id>/', EditarAvisoView.as_view(), name='editar_aviso'),
    path('mis-avisos/', MisAvisosView.as_view(), name='mis_avisos'),
    path('proveedores/', ListarProveedoresView.as_view(), name='listar_proveedores'),
    path('proveedores/nuevo/', CrearProveedorView.as_view(), name='crear_proveedor'),
    path('proveedores/editar/<int:proveedor_id>/', EditarProveedorView.as_view(), name='editar_proveedor'),
    path('proveedores/eliminar/<int:proveedor_id>/', EliminarProveedorView.as_view(), name='eliminar_proveedor'),
    path('gastos/', ListarGastosView.as_view(), name='listar_gastos'),
    path('gastos/nuevo/', CrearGastoView.as_view(), name='crear_gasto'),
    path('gastos/editar/<int:gasto_id>/', EditarGastoView.as_view(), name='editar_gasto'),
    path('gastos/eliminar/<int:gasto_id>/', EliminarGastoView.as_view(), name='eliminar_gasto'),
    path('consorcios/', ListarConsorciosView.as_view(), name='listar_consorcios'),
    path('consorcios/nuevo/', CrearConsorcioView.as_view(), name='crear_consorcio'),
    path('consorcios/editar/<int:consorcio_id>/', EditarConsorcioView.as_view(), name='editar_consorcio'),
    path('consorcios/eliminar/<int:consorcio_id>/', EliminarConsorcioView.as_view(), name='eliminar_consorcio'),
    path('departamentos/', ListarDepartamentosView.as_view(), name='listar_departamentos'),
    path('departamentos/nuevo/', CrearDepartamentoView.as_view(), name='crear_departamento'),
    path('departamentos/editar/<int:departamento_id>/', EditarDepartamentoView.as_view(), name='editar_departamento'),
    path('departamentos/eliminar/<int:departamento_id>/', EliminarDepartamentoView.as_view(), name='eliminar_departamento'),
    path('titularidades/', ListarTitularidadesView.as_view(), name='listar_titularidades'),
    path('titularidades/nuevo/', CrearTitularidadView.as_view(), name='crear_titularidad'),
    path('titularidades/editar/<int:titularidad_id>/', EditarTitularidadView.as_view(), name='editar_titularidad'),
    path('titularidades/eliminar/<int:titularidad_id>/', EliminarTitularidadView.as_view(), name='eliminar_titularidad'),
    path('perfiles/', ListarPerfilesView.as_view(), name='listar_perfiles'),
    path('perfiles/nuevo/', CrearPerfilView.as_view(), name='crear_perfil'),
    path('perfiles/editar/<int:perfil_id>/', EditarPerfilView.as_view(), name='editar_perfil'),
    path('perfiles/eliminar/<int:perfil_id>/', EliminarPerfilView.as_view(), name='eliminar_perfil'),
    path('usuarios/', ListarUsuariosView.as_view(), name='listar_usuarios'),
    path('usuarios/nuevo/', CrearUsuarioView.as_view(), name='crear_usuario'),
    path('usuarios/editar/<int:usuario_id>/', EditarUsuarioView.as_view(), name='editar_usuario'),
    path('usuarios/eliminar/<int:usuario_id>/', EliminarUsuarioView.as_view(), name='eliminar_usuario'),
]
