# Generated by Django 6.0.6 on 2026-06-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consorcios', '0002_departamento_metros_cuadrados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=20)),
                ('rubro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: YYYY-MM', max_length=7)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('pagada', models.BooleanField(default=False)),
                ('publicada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='GastoConsorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: YYYY-MM', max_length=7)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('ordinario', 'Ordinario'), ('extraordinario', 'Extraordinario')], default='ordinario', max_length=20)),
                ('alcance', models.CharField(choices=[('general', 'General'), ('por_departamento', 'Por departamento')], default='general', help_text='Solo aplica para gastos extraordinarios', max_length=20)),
                ('prorrateo', models.CharField(choices=[('proporcional', 'Proporcional a m2'), ('igualitario', 'Partes iguales')], default='proporcional', help_text='Criterio de division entre departamentos', max_length=20)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.consorcio')),
                ('departamentos', models.ManyToManyField(blank=True, help_text='Solo para extraordinarios por departamento', to='consorcios.departamento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expensas.proveedor')),
            ],
        ),
    ]
