# Generated by Django 6.0.6 on 2026-06-17 21:59

import django.db.models.deletion
import expensas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensa',
            name='periodo',
            field=models.CharField(help_text='Formato: YYYY-MM', max_length=7, validators=[expensas.validators.validar_formato_periodo]),
        ),
        migrations.AlterField(
            model_name='gastoconsorcio',
            name='periodo',
            field=models.CharField(help_text='Formato: YYYY-MM', max_length=7, validators=[expensas.validators.validar_formato_periodo]),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('expensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='expensas.expensa')),
            ],
        ),
    ]
