# Generated by Django 6.0.6 on 2026-06-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensas', '0002_alter_expensa_periodo_alter_gastoconsorcio_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
