# Generated by Django 6.0.6 on 2026-06-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='metros_cuadrados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
