# Generated by Django 6.0.6 on 2026-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0003_solicitudvinculacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvinculacion',
            name='condicion',
            field=models.CharField(choices=[('dueno', 'Dueño'), ('inquilino', 'Inquilino')], default='dueno', max_length=20),
        ),
    ]
