# Generated by Django 6.0.6 on 2026-06-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0004_add_condicion_to_solicitudvinculacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consorcio',
            name='cuit',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('consorcio', 'numero')},
        ),
    ]
