# Generated by Django 6.0.6 on 2026-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0005_unique_constraints_consorcio_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='titularidad',
            name='condicion',
            field=models.CharField(choices=[('dueno', 'Dueño'), ('inquilino', 'Inquilino')], default='dueno', max_length=20),
        ),
    ]
