# Generated by Django 6.0.6 on 2026-06-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0006_add_condicion_to_titularidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='usuario',
        ),
    ]
