# Generated by Django 6.0.6 on 2026-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='nota_respuesta',
            field=models.TextField(blank=True, default=''),
        ),
    ]
